version: '3.1'

services:
  web:
    build: ./nchan
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis-master

  redis-master:
    image: redis:4.0

  turntable:
    build: ./webapp
    ports:
      - "4242:5000"
    depends_on:
      - web
