version: '3.2'

services:
  nchan:
    build: ./nchan
    depends_on:
      - redis-master
      - webapp

  redis-master:
    image: redis:4.0

  webapp:
    build: ./webapp
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./webapp
        target: /usr/src/app
    environment:
      NCHAN_ROOT_URI: http://nchan
      FLASK_DEBUG: "true"
      PUBLIC_DOMAIN: "roundbroker.io"
      DATABASE_URI: postgresql://webapp:PleaseChangeMe!@database/roundbroker

  database:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: PleaseChangeMe!
      POSTGRES_DB: roundbroker

  reverse_proxy:
    build: ./reverse_proxy
    ports:
      - 80:80
    depends_on:
      - nchan
      - webapp
